on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh root@${{ secrets.SSH_HOST }} << EOF
            cd /var/www/myteacher-office
            git pull -f head
            cd backend
            npm i -f
            npm run build
            pm2 restart mycrm-api
          EOF
